name: Build and Test

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Run Tests
        run: ./gradlew test

      - name: Notify build completion
        run: |
          echo "✅ Build and test completed successfully!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Build Number: ${{ github.run_number }}"
